name: Scraper (Selenium Working)

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Output Folder
      run: mkdir -p output

    - name: Run Scraper
      run: python scraper.py

    - name: Upload CSV
      uses: actions/upload-artifact@v4
      with:
        name: scraped-data
        path: output/data.csv
